### ISSUE TITLE
Particle bounding box now in SWIFTs' top-level cells

### ISSUE THREAD

**Issue by MatthieuSchaller** [kyleaoman/swiftgalaxy#1]
This may be of interest: https://github.com/SWIFTSIM/swiftsimio/issues/121

**Comment by kyleaoman** [comment]
Thanks Matthieu. If I understand correctly the plan is for this to be integrated into swiftsimio - in that case I expect it will be picked up automatically by swiftgalaxy, but will keep an eye on it and see.
